baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ackbx"
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 10
  [[menu.main]]
    name = "Terms of Service"
    url = "/terms-of-service/"
    weight = 20
